### ISSUE TITLE
TypeError: join() takes no keyword arguments

### ISSUE THREAD

**Issue by nicofrand** [YunoHost/issues#1182]
What matters here: the python error `TypeError: join() takes no keyword arguments`

What I did:

 I tried to create a Redirect app to proxy the requests for the domain cozy.domain.tld to http://127.0.0.1:8080 which was already taken.

Action     
POST /apps
```
{"app":"redirect","args":"domain=cozy.domain.eu&path=%2F&redirect_path=http%3A%2F%2F127.0.0.1%3A8080&redirect_type=proxy&is_public=0","label":"Redirect"}
```
     
Trace
     
```
Traceback (most recent call last):
    File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 406, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
    File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 498, in process
    return func(**arguments)
    File "/usr/lib/moulinette/yunohost/app.py", line 728, in app_install
    args_odict = _parse_args_from_manifest(manifest, 'install', args=args_dict, auth=auth)
    File "/usr/lib/moulinette/yunohost/app.py", line 2034, in _parse_args_from_manifest
    return _parse_action_args_in_yunohost_format(args, action_args, auth)
    File "/usr/lib/moulinette/yunohost/app.py", line 2204, in _parse_action_args_in_yunohost_format
    raise MoulinetteError(errno.EINVAL, m18n.n('app_location_unavailable', "\n".join(apps=apps)))
TypeError: join() takes no keyword arguments
```

**Comment by Psycojoker** [comment]
That should fix it, I don't know if you can test that easily?

https://github.com/YunoHost/yunohost/commit/860f7408103dab24bd89d5428224490176c17d92

**Comment by sagaciouszu** [comment]
@nicofrand I'm still getting the same error after applying the fix:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/api.py", line 406, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 498, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/app.py", line 728, in app_install
    args_odict = _parse_args_from_manifest(manifest, 'install', args=args_dict, auth=auth)
  File "/usr/lib/moulinette/yunohost/app.py", line 2034, in _parse_args_from_manifest
    return _parse_action_args_in_yunohost_format(args, action_args, auth)
  File "/usr/lib/moulinette/yunohost/app.py", line 2204, in _parse_action_args_in_yunohost_format
    raise MoulinetteError(errno.EINVAL, m18n.n('app_location_unavailable', apps="\n".join(apps)))
TypeError: join() takes no keyword arguments
```

Any help would be fantastic, thank you!

**Comment by Psycojoker** [comment]
@sagaciouszu have you relaunch the API with "systemctl restart yunohost-api" before testing? I doesn't look like it (python open the file the show the code, it doesn't look at the code loaded in memory)

**Comment by sagaciouszu** [comment]
@Psycojoker Sigh. That seems to have fixed it. Thanks. I feel dumb because I didn't do that. 😋

**Comment by Psycojoker** [comment]
@sagaciouszu cool, thanks for confirming that it works :)

I'm closing this issue then (while it's not released yet it's in the testing)
