### ISSUE TITLE
Theming : custom_overlay.css isn't loaded anymore since 3.7

### ISSUE THREAD

**Issue by SiM** [YunoHost/issues#1562]
Hi,

On a YNH instance where I have a custom theme, I realized that the YNH button (#ynh-overlay-switch) present in applications was back to the default one.
While inspecting the loaded files, I notice that the custom_overlay.css file is no longer loaded, which explains this.

I tried enabling default themes, I tried on another YNH instance : I have the same behavior. No matter if the app is on a subdomain or subfolder.

yunohost --version on the two instance tested : 
```
yunohost:
  repo: stable
  version: 3.7.1.1
yunohost-admin:
  repo: stable
  version: 3.7.1.1
moulinette:
  repo: stable
  version: 3.7.1
ssowat:
  repo: stable
  version: 3.7.1.1
```

```
yunohost:
  repo: now
  version: 3.7.0.12
yunohost-admin:
  repo: now
  version: 3.7.0.4
moulinette:
  repo: now
  version: 3.7.0.2
ssowat:
  repo: now
  version: 3.7.0.3
```

**Comment by alexAubin** [comment]
>While inspecting the loaded files, I notice that the custom_overlay.css file is no longer loaded, which explains this.

How did you notice exactly ? Are you referring to Firefox's network debugger tab ?

**Comment by SiM** [comment]
> Are you referring to Firefox's network debugger tab ?

Yes

**Comment by alexAubin** [comment]
Hmmmm could it be that maybe this is fixed by https://github.com/YunoHost/yunohost/pull/925/files ?

**Comment by SiM** [comment]
I changed the file `/etc/nginx/conf.d/yunohost_panel.conf.inc` according to your link and restarted nginx : nothing changes.

It's weird because if I look in firefox the source code of an app, regarding ynh css or js I have this line : 
`    <script type="text/javascript" src="/ynh_portal.js"></script><link type="text/css" rel="stylesheet" href="/ynh_overlay.css"></link><script type="text/javascript" src="/ynhtheme/custom_portal.js"></script><link type="text/css" rel="stylesheet" href="/ynhtheme/custom_overlay.css"></link></head>`
which seems ok !

But in Firefox's network debugger tab I see that `custom_portal.js` and `custom_portal.css` are loaded (also `ynh_portal.css`, `ynh_portal.js` (three time !), `ynh_overlay.css` (twice))

 :thinking:

**Comment by ghost** [comment]
For info, I didn't dig too much yet but I have the same issue: custom overlay doesn't load anymore.
And https://github.com/YunoHost/yunohost/pull/925 (even it actually fixes another problem I have with 3.7 ;) ) doesn't help here.

**Comment by alexAubin** [comment]
So to try to clarify : 
- you confirm that the inclusion of custom_overlay.css exists in the html code
- it's loaded according to network debugger
- ... but you don't see the effect being applied on your page ?

Note that the fact that you are seeing the assets loaded multiple times is probably because of the 'yunohost button' pre-loading an iframe containing the yunohost portal, which also includes those (yea that's a bit of a mess)

That could also explain why you're seeing the custom_overlay.css loaded in the debugger (because it could be about loading in the iframe and not the original page). But that doesn't really explain why it would show in the html code and not be loaded. (Dunno if that makes sense)

Anyway, I'd happily spend a few minutes investigating if you have a way to reproduce this or if you can share your domain name (through a private mean if that matters)

**Comment by SiM** [comment]
Thank you @alexAubin for your time :+1: 

> you confirm that the inclusion of custom_overlay.css exists in the html code

Yes

> it's loaded according to network debugger

No, it **isn't loaded**

> ... but you don't see the effect being applied on your page ?

Indeed


**To sum up in other words :**

- CSS and JS included in the html code seems to be the good ones... 
- ...but those really loaded (according to network debugger) are not (some not included are loaded (ynh_portal.css), some are loaded several times (ynh_portal.js), some included are not loaded (custom_overlay.css))

**Steps to reproduce:**

1. Activate a theme ("clouds") on one YNH instance:
Add the line `"theme" : "clouds",` in `/etc/ssowat/conf.json.persistent` (according to https://yunohost.org/#/theming)

2. Go to you YNH portal (the overlay switch must be a cloud) and open an app (the overlay switch must be default YNH icon instead of a cloud) -  (refresh with "Ctrl+Maj+R" if needed) 

3. Inspect html code and network debugger to see which files are included and loaded

**Comment by eauchat** [comment]
@alexAubin I have the same issue on my server, so if you want I can send you infos in a PM.

I was trying to figure out what's going on now.
I can't get to open the themes files in the browser, maybe that's what's causing the issue.
From what I understand from that part of the ssowat code (that I had forgotten but I think I wrote ;)) I should be able to access my themes elements under:
 - `https://mydomain.tld/ynhtheme/custom_overlay.css`,
 - `https://mydomain.tld/ynhtheme/custom_portal.js`,
 - `https://mydomain.tld/ynhtheme/myCustomOverlayImage.png`...
But when I try to load them, I'm redirected to the portal page.

So maybe I'm doing something wrong, or could it be that those files are not being redirected to properly?

**Comment by micoots** [comment]
I can advise that I'm running the latest YNH and when I make the overlay ccs changes they don't work. The Yunhost logo keeps showing up (while the other main logo on login screen etc works fine).

I hope there's a fix for this coming?

**Comment by SiM** [comment]
Hi,
Wanting to solve this minor but annoying problem, I investigated again.

Contrary to what I wrote above, the missing files (custom_overlay.css and custom_portal.js) are trying to be loaded, but there is a 404.
Indeed, the requested URL are 
```
https://APP_URL/ynhtheme/custom_overlay.css 
https://APP_URL/ynhtheme/custom_portal.js
```

Seems that 'ynhtheme' is a variable and is not anymore replaced by the correct path (that must be '/yunohost/sso/assets/themes/THEME_NAME/')

I found that these url are defined in 'yunohost_panel.conf.inc' file (located in templates/nginx/plain), but I'm not sure how to go any further. 
@alexAubin if you can point me in a direction I might try to go a step further.

**Comment by kay0u** [comment]
@SiM You should take a look here: https://github.com/YunoHost/yunohost/blob/stretch-unstable/data/templates/nginx/plain/yunohost_panel.conf.inc

But I think it's already fixed with this commit: https://github.com/YunoHost/yunohost/commit/4968f1aa7df184c9c731a2fb3c2d4f4aa04a719e#diff-20dd296e527e737fe1f4799853491777

Are you still in 3.7.x? This fix should be present in 3.8

**Comment by SiM** [comment]
@kay0u I've upgraded to 3.8 for a while now and unfortunately the problem is still there. :(

I had a look on this file and saw this commit but as @curious-jeremy said earlier (https://github.com/YunoHost/issues/issues/1562#issuecomment-619139768), this doesn't fix this issue.

This file hasn't been modified between 3.6 and 3.7, so I guess the problem must come from somewhere else?

**Comment by kay0u** [comment]
Have you regenerated your nginx conf?

**Comment by SiM** [comment]
Yes.
I also tried in different YNH instances, tried different themes, always the same issue.
Can you reproduce the issue on your side? (I have described step to reproduce a few posts above: https://github.com/YunoHost/issues/issues/1562#issuecomment-620496591)

**Comment by kay0u** [comment]
No I can't reproduce it, on my ynh-dev and my production server. I have a nice clouds theme :-)

```
yunohost: 
  repo: stable
  version: 3.8.4.8
yunohost-admin: 
  repo: stable
  version: 3.8.3.4
moulinette: 
  repo: stable
  version: 3.8.1.2
ssowat: 
  repo: stable
  version: 3.8.0.1
```

If you want more logs, you can add the line `"logging": "debug",` in `/etc/ssowat/conf.json.persistent` (please remove it when you have done :-)), reload nignx, and inspect logs:
```
systemctl reload nginx
journalctl -f /var/log/nginx/ssowat.log
```
If you refresh your sso portal in your browser you should see something related to these files

On my ynh-dev I got:
```
[DEBUG Tue Jun 16 08:23:35 2020] Serving portal uri /yunohost/sso/assets/css/ynh_portal.css (if the corresponding file exists)
[DEBUG Tue Jun 16 08:23:35 2020] Serving portal uri /yunohost/sso/assets/themes/clouds/custom_portal.css (if the corresponding file exists)
[DEBUG Tue Jun 16 08:23:35 2020] Serving portal uri /yunohost/sso/assets/js/ynh_portal.js (if the corresponding file exists)
[DEBUG Tue Jun 16 08:23:35 2020] Serving portal uri /yunohost/sso/assets/themes/clouds/custom_portal.js (if the corresponding file exists)
[DEBUG Tue Jun 16 08:23:35 2020] Serving portal uri /yunohost/sso/assets/themes/clouds/background.jpg (if the corresponding file exists)
[DEBUG Tue Jun 16 08:23:35 2020] Serving portal uri /yunohost/sso/assets/themes/clouds/cloud.png (if the corresponding file exists)
```

**Comment by ghost** [comment]
I had one more look to that, and from the Firefox debug console I can see this message:
`The resource from “my.domain/yunohost/sso/” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff)`

In order to go one step further, I removed the `nosniff option` from the nginx conf and the message is a little bit more explicit:
`The stylesheet my.domain/yunohost/sso/ was not loaded because its MIME type, “text/html”, is not “text/css”.`

And indeed the URL which is loaded is not pointing to a CSS resource but to a HTML page. Looks like there is a bad redirection somewhere, making the CSS unreachable.
I tried a few tweaks, but with no luck.

**Comment by SiM** [comment]
@kay0u I think there is a misunderstanding :) 
The problem is not on sso portal (things are displayed properly), but on apps: the overlay button is the default one because of not loading custom_overlay.css 
Can you reproduce the problem on apps?

On sso portal I have the same log lines than you and the theme is displaying well.

Anyway @curious-jeremy may be you are pointing a good direction. Same behaviour here.
See my firefox network debugger: https://framapic.org/iwSpegWhdZeq/0r4tkMwxUnNr.png

```
yunohost: 
  repo: stable
  version: 3.8.4.8
yunohost-admin: 
  repo: stable
  version: 3.8.3.4
moulinette: 
  repo: stable
  version: 3.8.1.2
ssowat: 
  repo: stable
  version: 3.8.0.1

```

**Comment by kay0u** [comment]
> @kay0u I think there is a misunderstanding :)

Yes, I know it's in title, but I wasn't talking about `custom_overlay.css`. :-)

So, after a long debugging session, I finally found the problem, I'm gonna create a PR

**Comment by SiM** [comment]
Big thanks @kay0u  :pray:

**Comment by kay0u** [comment]
You can `apt update && apt upgrade` your server, the fix should be there :-)
