### ISSUE TITLE
Changing user password for user in web admin does not change it

### ISSUE THREAD

**Issue by artlog** [YunoHost/issues#1812]
I was wondering if i am the only one. Version 4.2.4 ( after many upgrades )
Discovered that today after a user lost his password.
Creating a new user with password does work, but changing user password from web admin does not.
I had to do it in phpldapadmin using 'clear' password that ends into 'crypt' once saved.
I tried with another user and hit same problem, didn't yet investigated it more deeply.

**Comment by alexAubin** [comment]
Can you elaborate on what you mean by "does not work"

**Comment by alexAubin** [comment]
We released a fix yesterday that should fix the issue, can you confirm that you're up to date for packages yunohost and moulinette ?

**Comment by alexAubin** [comment]
(Oh and now that I think about it, if you just upgraded moulinette yesterday night, you may have to manually restart the API with `systemctl restart yunohost-api`, or in the webadmin > Services > yunohost-api > Restart)

**Comment by artlog** [comment]
i just did this upgrade :+1: 
moulinette (de 4.2.2 à 4.2.3.1)
ssowat (de 4.2.2 à 4.2.3)
yunohost-admin (de 4.2.2 à 4.2.3)
yunohost (de 4.2.4 à 4.2.5.2)

and restarting yunohost-api.

yet i still can't get it working, have to check it again.

**Comment by artlog** [comment]
i may have a bigger problem, i can restart api with systemctl but not in webadmin, Service menu does not expand.

**Comment by artlog** [comment]
my system might not be clean, it is a production system that did receive some manual hacks over last two years, so this might not be relevant.

my service problem is due to a js script missing ( or wrong version )

109.210.47.42 - - [26/May/2021:16:15:44 +0200] "GET /yunohost/admin/js/views/service/list.e997feb7.js HTTP/2.0" 404 125 "https://xxxxxxxxx/yunohost/admin/" "Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0"

 ls /usr/share/yunohost/admin/js/views/service/list.e997feb7.js 
ls: impossible d'accéder à '/usr/share/yunohost/admin/js/views/service/list.e997feb7.js': Aucun fichier ou dossier de ce type
 ls /usr/share/yunohost/admin/js/views/service/
info.77e9ee00.js  info.77e9ee00.js.map	list.412c320e.js  list.412c320e.js.map

this is another issue but i don't catch why either.

UPDATE : this was unrelated to described problem, and i fixed it at client side by cleaning all cookies and stored data for server, it may be that upgrade change some .js references and are not well reflected in browser cache.

**Comment by artlog** [comment]
Since i can't rely on this production system i did test is on my ynh-dev environment that i upgrade with latest version.

I get very same problem : 
  - i can create a user in webadmin with a password
  - i can log in with that user and this password into yunohost  portal
  - if i use again webadmin and edit user with a new password *it keep the old one.*
  - i can change my user password though phpldapadmin
  - i can change my user password knowing the current one using change passowd in portal.

**Comment by artlog** [comment]
here a video of my problem : https://pire.artisanlogiciel.net/videos/watch/a2e74574-8c54-40f4-9ce2-56554f1debb4

**Comment by shukon** [comment]
I experience this problem as well. Just upgraded to the latest versions and restartet the api (via webinterface, that was not an issue), but it didn't fix it.

```
moulinette: 4.2.3.1
yunohost: 4.2.5.2
ssowat: 4.2.3
yunohost-admin: 4.2.3
```

I didn't check whether using phpldapadmin works.
My only manual tweaking I currently recall is the installation of two small docker containers, which shouldn't have much to do with the login.

If I can provide anything to let you analyze this, let me know.

EDIT: `sudo yunohost user update USER -p NEW_PASS` works just fine, so I assume it's the API.

**Comment by shukon** [comment]
I just stumbled upon this again with another server. Thanks a lot for the fix, but is it already merged/released? Or better still: Where can I find information on the yunohost release cycle?

**Comment by alexAubin** [comment]
It's supposed to already be released, but i'm guessing it doesn't actually fixes the issue considering many people still report it :/

**Comment by zamentur** [comment]
It might be a problem with yunohost-api to restart a suser said after restart the server it works.
