### ISSUE TITLE
Trixie: Let's Encrypt certificate renewal fails with "TypeError: argument 'data': from_buffer() cannot return the address of a unicode object"

### ISSUE THREAD

**Issue by eduardomozart** [YunoHost/issues#2700]
### Describe the bug

Turns out that something in the algorithm to renew Let’s Encrypt certificates changed upon upgrading to Trixie.

### Context

Turns out it might not be that unusual of a problem - [searching for the error message](https://stackoverflow.com/questions/59766666/typeerror-from-buffer-cannot-return-the-address-of-a-unicode-object#comment105683420_59766666) shows that it should be easily fixable. Quote:

> Under Python 3, it can be converted accordingly with `bytes.fromhex(args.secret)`, whereas `args.secret.decode("hex")` no longer works

- Hardware: VPS bought online
- YunoHost version: 13.0
- I have access to my server: Through SSH | through the webadmin | direct access via keyboard / screen
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
  - If yes, please explain:
- Using, or trying to install package version/branch:
- If upgrading, current YunoHost version: 

### Logs

```
2025-11-05 14:10:38,241 ERROR    yunohost.certmanager.certificate_renew - Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yunohost/certificate.py", line 422, in certificate_renew
    _fetch_and_enable_new_certificate(domain, no_checks=no_checks)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yunohost/certificate.py", line 526, in _fetch_and_enable_new_certificate
    _prepare_certificate_signing_request(domain, domain_key_file, TMP_FOLDER)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yunohost/certificate.py", line 635, in _prepare_certificate_signing_request
    private_key = serialization.load_pem_private_key(pem_file.read(), password=None)
TypeError: argument 'data': from_buffer() cannot return the address of a unicode object

2025-11-05 14:10:38,242 ERROR    yunohost.certmanager.certificate_renew - argument 'data': from_buffer() cannot return the address of a unicode object
2025-11-05 14:10:38,248 ERROR    yunohost.certmanager.certificate_renew - Sending email with details to root ...
```

Full log: https://paste.yunohost.org/raw/oqikititox

**Comment by Salamandar** [comment]
Should be fixed by https://github.com/YunoHost/yunohost/commit/a127563f62ed9193a83ca90b5c390c2431bfc1a3.

**Comment by eduardomozart** [comment]
Tried that (edited ``/usr/lib/python3/dist-packages/yunohost/certificate.py``), but it is still broken for me on WebUI after applying the fix, but I can renew it just fine through Terminal now:

```
$ sudo yunohost domain cert install webmail.maindomain.tld 
Info: Now attempting install of certificate for domain webmail.maindomain.tld!
Success! Configuration updated for 'dnsmasq'
Info: Parsing account key...
Info: Parsing CSR...
Info: Found domains: webmail.nethouse.inf.br
Info: Getting directory...
Info: Directory found!
Info: Registering account...
Info: Registered!
Info: Creating new order...
Info: Order created!
Info: Verifying webmail.nethouse.inf.br...
Info: webmail.nethouse.inf.br verified!
Info: Signing certificate...
Info: Certificate signed!
Success! Let's Encrypt certificate now installed for the domain 'webmail.maindomain.tld'
```

**Comment by Salamandar** [comment]
I guess you need to restart the yunohost-api server before running stuff from the webadmin.

**Comment by eduardomozart** [comment]
You were right! After rebooting, it started working as expected on YunoHost WebUI too. Thank you!
